require "plugins.config.lsp.servers.sumneko_lua"
require "plugins.config.lsp.servers.texlab"
require "plugins.config.lsp.servers.rust_analyzer"
require "plugins.config.lsp.servers.pylance"
require "plugins.config.lsp.servers.efm"
require "plugins.config.lsp.servers.cmake"
