-- require 'plug-config.treesitter'
require 'plug-config.telescope'
require 'plug-config.lualine'
require 'plug-config.treesitter'
require 'plug-config.bufferline'
require 'plug-config.nvimtree'
require 'plug-config.whichkey'
require 'plug-config.floaterm'
require 'plug-config.gitsigns'
require 'plug-config.lsp'
require 'plug-config.lspsaga'
require 'plug-config.colorizer'
require 'plug-config.diffview'
