require 'plug-config.treesitter'
require 'plug-config.telescope'
require 'plug-config.lualine'
require 'plug-config.bufferline'
require 'plug-config.lsp'
require 'plug-config.nvimtree'
require 'plug-config.whichkey'
require 'plug-config.floaterm'
