#!/bin/bash
_run() {
    pgrep -x "${1}" >/dev/null || "$@" &
}

_run sxhkd

INTERNAL_MONITOR="eDP-1-1"
EXTERNAL_MONITOR="HDMI-0"
if [[ $1 == 0 ]]; then
    if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
        bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 0
        bspc monitor "$INTERNAL_MONITOR" -d 10
        bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
    else
        bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6 7 8 9 0 10
    fi
fi

# bspc config border_radius 10
bspc config border_width 2
bspc config borderless_monocle true
bspc config focused_border_color "#353b45"
bspc config gapless_monocle true
bspc config normal_border_color "#282c34"
bspc config single_monocle false
bspc config split_ratio 0.50
bspc config top_padding 20
bspc config window_gap 8

bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
bspc config focus_follows_pointer true

_run xbanish
_run dunst
_run flameshot
_run picom
_run kbd_layout
_run nm-applet
_run clipcatd
_run xsetroot -cursor_name left_ptr
_run redshift
(
    "${HOME}/.local/bin/monitor_setup"
    "${HOME}/.local/bin/fix_speed"
    "${HOME}/.local/bin/kbd_layout"
    feh --bg-scale ~/Pictures/unknown.png
    xset r rate 200 120
) &
